### ISSUE TITLE
Teens rule is not applied for 111 et cetera

### ISSUE THREAD

**Issue by fiducioso-dan** [amesee/ordinal#1]
Actual result:

```
$ node
> const ord = require("ordinal").english;
undefined
> ord(111)
'111st'
> ord(112)
'112nd'
```

Expected result:

```
$ node
> const ord = require("ordinal").english;
undefined
> ord(111)
'111th'
> ord(112)
'112th'
```

Wikipedia has a good summary of the [rules in English](https://en.wikipedia.org/wiki/English_numerals#Ordinal_numbers).
![screenshot from 2015-11-03 06-24-59](https://cloud.githubusercontent.com/assets/12561563/10909087/b2668ae6-81f3-11e5-8ca2-12b670988988.png)

**Comment by amesee** [comment]
Thanks for reporting this. Sorry it took me a while to address it. To be honest I just found today that this issue even existed.

Bug fixed and published as version 0.0.3 at https://www.npmjs.com/package/ordinal.
